### ISSUE TITLE
Elements of called view always nil

### ISSUE THREAD

**Issue by MauMaxxa** [SSA111/SSASideMenu#10]
When i put it in my project, with storyboard, i did everything like in the example, but if i instantiate, for example, a collectionviewcontroller, the collection view is always nil. It looks like the istantiated view always has no child elements..

**Comment by SSA111** [comment]
Can you provide an example project, where this is the case?

**Comment by MauMaxxa** [comment]
https://github.com/SSA111/SSASideMenu

here it's a similar situation

**Comment by MauMaxxa** [comment]
I solved doing this:

func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
        let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        switch indexPath.row {
        case 0:
        
            sideMenuViewController?.contentViewController = UINavigationController(rootViewController: (storyBoard.instantiateViewControllerWithIdentifier("ListaPagine") as? HomepageVC)!)
            
            sideMenuViewController?.hideMenuViewController()
            break
        case 1:
            
            
            sideMenuViewController?.contentViewController = UINavigationController(rootViewController: (storyBoard.instantiateViewControllerWithIdentifier("ProfiloVC") as? ProfiloVCViewController)!)
            sideMenuViewController?.hideMenuViewController()
            break
        default:
            break
        }
        
        
    }

but.. will it slow instantiating a new nav. controller on each selection?

**Comment by SSA111** [comment]
@MauMaxxa This is the right way to do it for now.

**Comment by lifeisfoo** [comment]
I'm facing the same issue, is there any update about this?

**Comment by azamk100** [comment]
Does instantiating a new controller each time have performance impacts? Is this advisable?

**Comment by rameshpjpti** [comment]
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

  let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
  var destinationVC : String

  tableView.deselectRowAtIndexPath(indexPath, animated: true)

  switch indexPath.row {
  case 0: destinationVC = "FirstViewController"
  case 1: destinationVC = "SecondViewController"
  default: destinationVC = "FirstViewController" // go back to the "home" screen
  }
  var destinationViewController = mainStoryboard.instantiateViewControllerWithIdentifier(destinationVC) as? UIViewController

  if let navController = destinationViewController as? UINavigationController {
    destinationViewController = navController.visibleViewController
  }

  sideMenuViewController?.contentViewController = UINavigationController(rootViewController: destinationViewController! )
  sideMenuViewController?.hideMenuViewController()

}

**Comment by rameshpjpti** [comment]
I solve this issue in swift 3

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        var destinationVC : String
        
        tableView.deselectRow(at: indexPath, animated: true)
        
        switch indexPath.row {
        case 0: destinationVC = "FirstViewController"
        case 1: destinationVC = "WaterCalcVC"
        default: destinationVC = "FirstViewController"
        }
        
        var destinationViewController = mainStoryboard.instantiateViewController(withIdentifier: destinationVC) as? UIViewController
        
        if let navController = destinationViewController as? UINavigationController {
            destinationViewController = navController.visibleViewController
        }
        
        sideMenuViewController?.contentViewController = UINavigationController(rootViewController: destinationViewController! )
        sideMenuViewController?.hideMenuViewController()
    }
