### ISSUE TITLE
Starts Lagging after 20-30 times, When Cycling to different VCs

### ISSUE THREAD

**Issue by djaygit** [SSA111/SSASideMenu#11]

**Comment by SSA111** [comment]
@djaygit Is this tested on a device?

**Comment by djaygit** [comment]
yes happens on all ios 7 and ios 8 both

**Comment by djaygit** [comment]
any updates @SSA111 ?

**Comment by SSA111** [comment]
@djaygit Can't seem to reproduce in the two examples provided. Please provide an example of your setup. Thank you.

**Comment by djaygit** [comment]
@SSA111 whats your email?

**Comment by PickMe** [comment]
Hi, i got the same problem. I think its about that the old view controller are not dismissed....
 I.e. push notification are received multiple times - for each view controller ever opened.

**Comment by djaygit** [comment]
@PickMe Looks like I cannot reply to your email because your mail is not setup or server is down or seomthing.

**Comment by PickMe** [comment]
Hi, should work now. Try again!

**Comment by djaygit** [comment]
Nope still same error.

**Comment by SSA111** [comment]
Please provide an example branch here om Github if possible. Thank you.

**Comment by flandy84** [comment]
yes, same here. 

viewcontollers seems to stay in memory forever (leak?!), they never releasing memory (deinit method is never called) , when they are added to side-menu Property

example:

sideMenuViewController?.contentViewController = FirstViewController()
sideMenuViewController?.contentViewController = SecondViewController()
sideMenuViewController?.contentViewController = FirstViewController()

-->
    deinit{
    
    }
deallocation-Method of set Viewcontrollers (FirstViewController, SecondViewController....etc) is never called.

simple to reproduce.
and maybe to fix?!

**Comment by SSA111** [comment]
Can't seem to reproduce. 
Remember to call hideMenuViewController, after setting the contentViewController. 
![output_yvqnxm](https://cloud.githubusercontent.com/assets/4737688/8940505/a88b9a78-356a-11e5-964b-9591d2eeabc3.gif)

**Comment by flandy84** [comment]
to reproduce the memory-leak-effect, use one of your provided examples ("Storyboard", or "Simple").
add an empty deinit{} method to FirstViewcontroller.swift class and set a breakpoint to this method.
switch in your example menu between "Home" and "Calender" and you will see the deinit-breakpoint/method is never called --> memory leaks, Viewcontrollers added wirll neved be released in current implementation of SSASideMenu

**Comment by SSA111** [comment]
Ah okay. Can I close this issue then ?

**Comment by flandy84** [comment]
Close it
