### ISSUE TITLE
Storyboard example; working with multiple screens

### ISSUE THREAD

**Issue by Neejoh** [SSA111/SSASideMenu#13]
No trouble getting the example to work, but I need some help setting up the workflow working with multiple screens. I am new to Swift, so any nudge into the right direction would be very well appreciated. 

In my storyboard I have the default setup from the example, with one Navigation Controller with the Storyboard ID of "FirstViewController". When I place a label on the connected ViewController it shows up after building the app. But when switching between Home to Calendar, and back to Home again, the screen is empty.

I basically want to add another Navigation Controller for SecondViewController to be able to design the second screen (with just some labels and buttons, for example). But doing this (and setting the Storyboard ID / custom class) it just ignores my newly created ViewController

```swift
switch indexPath.row {
// [..]
case 1:
    sideMenuViewController?.contentViewController = UINavigationController(rootViewController: SecondViewController())
// [..]
}
```

Can I somehow change the "contentViewStoryboardID" in the case above, somehow? Or better yet, what would be the correct way to go about working with multiple screens and ViewControllers?

**Comment by SSA111** [comment]
@Neejoh 
You will need to instantiate the viewcontrollers from your Storyboard. (I will update the Storyboard example project to reflect this soon). 
Write: 
    sideMenuViewController?.contentViewController = UINavigationController(rootViewController: (storyBoard.instantiateViewControllerWithIdentifier("StoryboardContenID") as? UIViewController)!)
sideMenuViewController?.hideMenuViewController()

Instead of:

sideMenuViewController?.contentViewController = UINavigationController(rootViewController: SecondViewController())
sideMenuViewController?.hideMenuViewController()

**Comment by Neejoh** [comment]
I've been trying to get it to work but I can't seem to get my way around the following error:
`2015-06-11 14:07:29.913 SSASideMenuStoryboardExample[6496:1445658] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing a navigation controller is not supported'`

My current code;
```swift
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
  
  let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
  var destinationViewController : String

  tableView.deselectRowAtIndexPath(indexPath, animated: true)
  
  switch indexPath.row {
  case 0:
    destinationViewController = "FirstViewController"
  case 1:
    destinationViewController = "SecondViewController"
  default:
    destinationViewController = "FirstViewController" // go back to the "home" screen
  }

  // This goes through a navigationController, which gives the following error
  // 2015-06-11 14:07:29.913 SSASideMenuStoryboardExample[6496:1445658] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing a navigation controller is not supported'
  sideMenuViewController?.contentViewController = UINavigationController(rootViewController: (mainStoryboard.instantiateViewControllerWithIdentifier(destinationViewController) as? UIViewController)!)
  sideMenuViewController?.hideMenuViewController()
}
```

An example would be great.

**Comment by Neejoh** [comment]
I figured it out, thanks to [Paul Hegarty's Stanford's course](https://youtu.be/gjl2gc70YHM?t=54m00s) on multiple MVC's.

I ended up with the following code, which allows the destination ViewController (FirstViewController/SecondViewController/[..]) to be either wrapped in a NavigationController...or not.

```swift
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
  
  let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
  var destinationVC : String

  tableView.deselectRowAtIndexPath(indexPath, animated: true)

  switch indexPath.row {
  case 0: destinationVC = "FirstViewController"
  case 1: destinationVC = "SecondViewController"
  default: destinationVC = "FirstViewController" // go back to the "home" screen
  }
  
  // If the destination ViewController is actually a UIViewController, and not wrapped in a ViewController, that will be
  // the destination ViewController
  var destinationViewController = mainStoryboard.instantiateViewControllerWithIdentifier(destinationVC) as? UIViewController
  
  // If the destination ViewController is a NavigationController, not a ViewController, we want the top view controller
  // on it's stack to be shown
  if let navController = destinationViewController as? UINavigationController {
    destinationViewController = navController.visibleViewController
  }

  // We've got our destination ViewController ready, time to show it and hide the MenuViewController
  sideMenuViewController?.contentViewController = UINavigationController(rootViewController: destinationViewController! )
  sideMenuViewController?.hideMenuViewController()

}
```

**Comment by SSA111** [comment]
I am glad that you got it to work.
