### ISSUE TITLE
Navigation bar not showing on launch

### ISSUE THREAD

**Issue by gristoi** [SSA111/SSASideMenu#19]
Hi, firstly this is a great piece of work. 

I am trying my hardest to get this working. the issue i am having is as soon as i launch my app the navigation bar at the top of the view is not there.

But as soon as i swipe left and click on the home button again then the navigation controller bar appears a normal. Do you have an idea what could cause this?

I have attached screenshots of my storyboard setup and launch image of the app. the code to add the left button and title is exactly the same as yours too

thanks :)

![screen shot 2015-09-19 at 13 28 30](https://cloud.githubusercontent.com/assets/1233206/9976150/7909057e-5ed2-11e5-8173-bab410aa3784.png)
![screen shot 2015-09-19 at 13 28 47](https://cloud.githubusercontent.com/assets/1233206/9976149/79080250-5ed2-11e5-95e7-697c6977cad3.png)

**Comment by SSA111** [comment]
iOS 9?

**Comment by gristoi** [comment]
Hi, this was my stupidity, the menu is working great.  It just wasnt very clear that the nav controller in the storyboard example had the firstViewController storyboard id on it, and not the firstViewController itself. so im closing the issue :)
