### ISSUE TITLE
unwanted area between menu and content

### ISSUE THREAD

**Issue by flandy84** [SSA111/SSASideMenu#20]
Hi,

we've discovered a strange issue in our iPad testings.

![image](https://cloud.githubusercontent.com/assets/1314935/10302052/dc0760ba-6c08-11e5-848a-fb37ebe71e2f.png)

steps to reproduce issue:

* hold iPad in landscpae (menu should be closed)
* lay down iPad flat (on a table)
* open menu

any ideas what's going wrong here?

**Comment by flandy84** [comment]
config/setup to reproduce issue:
-device with iOS8. 
-app supports landscape+portrait

slide-menu config:
        type = .Slip
        view.backgroundColor = UIColor.blackColor()
        configure(SSASideMenu.MenuViewEffect(fade: true, scale: false, scaleBackground: false))
        configure(SSASideMenu.ContentViewEffect(alpha: 1.0, scale: 1, landscapeOffsetX: -200, portraitOffsetX: -75))
        bouncesHorizontally = false

**Comment by SSA111** [comment]
Thank you for the details. Will try to fix. Or if you find a solution a PR is welcome.

**Comment by flandy84** [comment]
I'm not sure, but i think you should'nt use Device/physics-specific methods (like this UIDevice.currentDevice().orientation) to layout user-interface elements. (maybe System/interface-specific checks are a better approach, may be this UIApplication.sharedApplication().statusBarOrientation).

Another idea: some deprecated methods can make problems on new iOS-versions (iOS8 or iOS9) like willAnimateRotationToInterfaceOrientation; maybe it's better so switch to a 'modern' adaptive-transition method?!

**Comment by SSA111** [comment]
The "UIDevice.currentDevice().orientation" is now changed to "UIApplication.sharedApplication().statusBarOrientation". Let me know if this work better.

**Comment by flandy84** [comment]
Seems to work better now. Thx

**Comment by SSA111** [comment]
Perfect. Closing for now.
