### ISSUE TITLE
Facebook Login Issue

### ISSUE THREAD

**Issue by cancem123** [SSA111/SSASideMenu#22]
I'm having an issue when I log via Facebook the top of navigation bar becomes under the status bar in iOS 8 and 9.

My progress is like this I click on the menu and it shows me the menu and I have a button that present the login view after I click on the Facebook login button the app takes me to the Facebook app and do the process and once it comes back I click on the view back the NavigationBar becomes under the status bar until I call the ViewController from the sideview and it becomes normal.

**Comment by LuaiKalkatawi** [comment]
Please can you check the link below I have added a sample from your project and you can see the issue from there.

https://www.dropbox.com/s/laak8oz2izjcpsb/SSASideMenu-master-4.zip?dl=0

**Comment by cancem123** [comment]
Please can you check the link below I have added a sample from your project and you can see the issue from there.

https://www.dropbox.com/s/laak8oz2izjcpsb/SSASideMenu-master-4.zip?dl=0

**Comment by SSA111** [comment]
Thank you. I will take a look at the sample.

**Comment by cancem123** [comment]
Hello Sebastian,
Is there any update?

**Comment by cancem123** [comment]
Hello @SSA111 ,
Is there any update to fix this issue?

**Comment by cancem123** [comment]
Hi @SSA111 did you test the app?
In any View Controller if you present a View Controller and close the app by clicking on the main button(iPhone device button) and open the app back the view becomes under the navigation bar becomes under the status bar.

**Comment by cancem123** [comment]
Fixed my issue by adding a NavigationController on the ViewController(SSASideMenu class ViewController) and it is working fine :)
