### ISSUE TITLE
Calling viewController from AppDelegate

### ISSUE THREAD

**Issue by LuaiKalkatawi** [SSA111/SSASideMenu#25]
I'm trying to open a viewController from didReceiveRemoteNotification in appDelegate but it is not doing anything while the same code is working fine in the LeftMenuViewController.Swift. So please how can I call the viewController from AppDelegate?

    func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {

        let sideView = SSASideMenu()
        let storyboard = UIStoryboard(name: "MyProfile", bundle: nil)
        let vc = storyboard.instantiateViewControllerWithIdentifier("MyProfileViewController")
                    
        sideView.contentViewController = vc
    }

**Comment by LuaiKalkatawi** [comment]
I have changed my code to the code below

    let sideMenu : SSASideMenu = SSASideMenu()
    let storyboard = UIStoryboard(name: "Basket&Payment", bundle: nil)
    let vc = storyboard.instantiateViewControllerWithIdentifier("BasketViewController") as! UINavigationController

    sideMenu.contentViewController = vc
    sideMenu.hideMenuViewController()
                    
    window?.rootViewController = sideMenu
    window?.makeKeyAndVisible()

but this time my navigationBar menu button doesn't make any action while this method gets called on each hit on the navigationBar menu button

    @IBAction func presentLeftMenuViewController() {
        sideMenuViewController?._presentLeftMenuViewController()
    }

**Comment by LuaiKalkatawi** [comment]
Fixed my issue by calling the viewController by this method

    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let vc = storyboard.instantiateViewControllerWithIdentifier("catViewController") as! UINavigationController

    (window?.rootViewController as! SSASideMenu).contentViewController = vc

**Comment by ArjunSa786** [comment]
hi LuaiKalkatawi
how to call another view controller instead of UINavigaioncontroller
for ex 
let storyboard = UIStoryboard(name: "Main", bundle: nil)
let vc = storyboard.instantiateViewControllerWithIdentifier("firstViewController") as! firstViewController

(window?.rootViewController as! SSASideMenu).contentViewController = vc

crash appear
how to solve this problem?

**Comment by mohammadshalhoob** [comment]
this code work with me 

            guard let vacanceDetailsTableViewController = AppDelegate.storyboard.instantiateViewController(withIdentifier: "vacanceDetailsTableViewController") as? vacanceDetailsTableViewController else{completionHandler(.noData);return}
            vacanceDetailsTableViewController.id = Int(id) ?? 0
            vacanceDetailsTableViewController.getVacanceData = true
            guard let SSASideMenuView = AppDelegate.storyboard.instantiateViewController(withIdentifier: "SSASideMenuView") as? SSASideMenu else{completionHandler(.noData);return}
            SSASideMenuView.contentViewController = vacanceDetailsTableViewController
            let nav = UINavigationController(rootViewController: SSASideMenuView)
            guard let SSASide = window?.rootViewController as? SSASideMenu else{completionHandler(.noData);return}
            SSASide.contentViewController = nav
            completionHandler(.noData)

**Comment by mohammadshalhoob** [comment]
and this to get top view or top Nav with ssasidemenu
 public class func topViewController(_ base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController,returnNav:Bool=false) -> UIViewController? {
        if let SSASide = base as? SSASideMenu {
            if let nav = SSASide.contentViewController as? UINavigationController{
                if returnNav{
                    return nav
                }else {
            return topViewController(nav.visibleViewController)
                }
            }else{ // without nav
            return topViewController(SSASide.contentViewController)
            }
        }
        if let nav = base as? UINavigationController {
            return topViewController(nav.visibleViewController)
        }
        
        if let tab = base as? UITabBarController {
            let moreNavigationController = tab.moreNavigationController
            
            if let top = moreNavigationController.topViewController, top.view.window != nil {
                return topViewController(top)
            } else if let selected = tab.selectedViewController {
                return topViewController(selected)
            }
        }
        
        if let presented = base?.presentedViewController {
            return topViewController(presented)
        }
        
        return base
    }
