### ISSUE TITLE
Side Menu Becomes White

### ISSUE THREAD

**Issue by cloudjanak** [SSA111/SSASideMenu#26]
![simulator screen shot 19-oct-2015 5 48 51 pm](https://cloud.githubusercontent.com/assets/7457258/10577537/b0bffb98-7689-11e5-91df-e02011df534a.png)

**Comment by cancem123** [comment]
Could you share your code? iOS 8 or 9?

**Comment by SSA111** [comment]
Set the backgroundColor to clearColor.

**Comment by cloudjanak** [comment]
Background color is already clear.it is not always clear but when i swipe from starting of lest screen than goes white for a second.

**Comment by SSA111** [comment]
Okay. Will make a fix asap.

**Comment by cloudjanak** [comment]
Thanks i am waiting for solution

**Comment by cloudjanak** [comment]
Any Hope now ??

**Comment by SSA111** [comment]
Should be fixed in the latest commit d0009c8. Let me know if it works.

**Comment by cloudjanak** [comment]
Thanks @SSA111
