### ISSUE TITLE
Not working on iOS 7.0.6 in iPhone 4S

### ISSUE THREAD

**Issue by gletsch** [SSA111/SSASideMenu#46]
On all devices and simulator i tested this so far it works really good. But now with 4s on 7.0.6 it shows on startup of the app the background of the menu with a light gray overlay instead of the firstView. No interaction possible at all.
Any suggestions?

**Comment by SSA111** [comment]
iOS 7 is currently not supported by the library, since iOS 8+ API's are being used. A PR implementing support for iOS 7 is appreciated.
