### ISSUE TITLE
Storyboard example

### ISSUE THREAD

**Issue by DigitalRogues** [SSA111/SSASideMenu#5]
Anyone have a storyboard example? I've been trying to adopt the storyboard technique from the original RESideMenu code base, but havent had much luck with getting the background image to draw properly using this code base with storyboards, although the menus do function.

**Comment by SSA111** [comment]
I will add a Storyboard Example shortly. Thank you for the request.

**Comment by smashkins** [comment]
Up! ;)

**Comment by SSA111** [comment]
Updated with Storyboard Example.
