### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value at this line outDragDropCollectionView.draggingDelegate = self

### ISSUE THREAD

**Issue by NuelNikhil** [SSA111/SSASideMenu#50]
I have a requirement in my project to implement a Side Menu as well as a drag and drop animation. For this I am using SSASide and for Drag and drop I am using [this](https://github.com/LiorNn/DragDropCollectionView) library. I have managed to implement both the libraries individually in my project and when I mixed up both the Side Menu and Drag and Drop animation I am getting an error which is the title of this issue. I had a chat with Drag and Drop library creator it can be found [here](https://github.com/LiorNn/DragDropCollectionView/issues/4)  he said there is nothing wrong with his library. I need both the libraries to work in a same ViewController. When I set this ViewController as the root viewcontroller in Appdelegate like this 

``````
```
``````

```
 let sideMenu = SSASideMenu(contentViewController: UINavigationController(rootViewController: HomeViewController()), leftMenuViewController: LeftMenuViewController(), rightMenuViewController: RightMenuViewController())
        sideMenu.backgroundImage = UIImage(named: "Background.jpg")
        sideMenu.configure(SSASideMenu.MenuViewEffect(fade: true, scale: true, scaleBackground: false))
        sideMenu.configure(SSASideMenu.ContentViewEffect(alpha: 1.0, scale: 0.7))
        sideMenu.configure(SSASideMenu.ContentViewShadow(enabled: true, color: UIColor.blackColor(), opacity: 0.6, radius: 6.0))
        sideMenu.delegate = self

        window?.rootViewController = sideMenu
        window?.makeKeyAndVisible()
```

```

I get the error mentioned in the title in ViewController at this line, please check the image


![error](https://cloud.githubusercontent.com/assets/7767550/14599439/f3a6ccf0-0574-11e6-8935-6f1ea635e1f4.jpeg)

is this occurs due to SSASideMenu??? Do I need any changes??? I need both to get work.
```

**Comment by SSA111** [comment]
Seems like you 'outDragDropCollectionView' is nil. Should not be an issue with the library. Closing for now, let me know if the error still occurs.
