### ISSUE TITLE
contentViewController as UITabbar

### ISSUE THREAD

**Issue by redongjika** [SSA111/SSASideMenu#8]
Hi,

I tried to customize the code so I can get a UITabbarController in lieu of the UIViewController you are using for the contentViewController.
Everything works fine for iOS8 but not for iOS7 where the tabbar is just not appearing (the shadow is though).
Do you have any idea about that issue?

Thank you and congrats for the code.

**Comment by SSA111** [comment]
@redongjika  Are you using Storyboards?

**Comment by redongjika** [comment]
Yes I do.
